FHG-2429/bug fix referral UI back navigation error when not on first page in search results
DFE-Digital/fh-referral-ui pull request #145
Opened 2023-03-01 16:44 UTC by alidfe

https://dfedigital.atlassian.net/browse/FHG-2429?atlOrigin=eyJpIjoiYTExZmU3NjcyZjNhNDVlNzlmMzUyZjgyZWQyNTYyZmYiLCJwIjoiaiJ9

2023-03-01 16:57 UTC, MartinBelton-gov submitted a review, later dismissed

2023-03-01 17:12 UTC, hardik-desai-kcl requested changes
Please add Unit tests to cover this code changes

2023-03-02 12:28 UTC, alidfe commented on src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/Search.cshtml.cs
>                  //distance = 32186.9 //212892.0
Removed

2023-03-02 14:17 UTC, alidfe commented
> Please add Unit tests to cover this code changes

Added legacy missing unit tests for Search page

2023-03-02 14:17 UTC, closed without merging